# name of your paladin
name: name goes here
# description of your paladin
description: description goes here
conditions: 
  # example items that must match in the hook payload
  # you can use dot notation for nested keys
  hook:
    branch: master 
    repository.name: foobar 
  # if you want this paladin to run on a schedule then set schedule 
  # equal to a cron string
  schedule: 0 0 0 0 0 
# if you are using hook, you can specify data here that
# is from the hook payload which you want to make available to
# the runner
data:
  - repository.name
# these are the blocks of code to be run by the runner
blocks:
  # specify the language
  # currently only 'python' and 'bash' are supported
  - language: python
    # add your code as a multiline string here
    code: |-
      # this is an example of a Python block
      print('hello world')
  - language: bash
    code: |-
      # this is an example of a bash block
      echo "hello world"