version: "3.9"
networks:
  isolation-network:
    driver: bridge
services:
  ceresdb:
    image: "ceresdb"
    environment:
      CERESDB_LOG_LEVEL: INFO
    ports:
      - "0.0.0.0:7437:7437"
    tty: true
  whitetail:
    image: "whitetail"
    environment:
      WHITETAIL_LOG_LEVEL: TRACE
    ports:
      - "0.0.0.0:9001:9001"
      - "0.0.0.0:9002:9002"
      - "0.0.0.0:9003:9003"
    depends_on:
      - ceresdb
    tty: true
    volumes:
      - ./test/operation.yaml:/tmp/whitetail/operations/operation.yaml
