apiVersion: v1
data:
  config.ini: |-
    [FILE_SYSTEM]
    ceres_home = ceres_home

    [DATA]
    data_encoding = utf-8
    max_groups = 32
    max_blocks = 8
    block_size = 65536
    insert_strategy = first

    [SERVER]
    server_port = 9090
    server_debug = yes
  schema.json: |-
    {
      "order": [
        "year",
        "month",
        "day",
        "hour",
        "minute",
        "second",
        "service",
        "message",
        "level",
        "timestamp"
      ],
      "fields": {
        "year": "int",
        "month": "int",
        "day": "int",
        "hour": "int",
        "minute": "int",
        "second": "int",
        "service": "str",
        "message": "str",
        "level": "str",
        "timestamp": "str"
      }
    }
kind: ConfigMap
metadata:
  name: ceres-config-configmap